[project]
name = "yescomusa-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb==1.1.2",
    "httpx==0.27.2",
    "jupyterlab==4.3.0",
    "pandas==2.2.3",
    "selectolax==0.3.25",
]
